version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ../../
      dockerfile: ops/docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_NAME=${REACT_APP_NAME}
