version: '3.7'

services:
  nextjs:
    build:
      context: ../../
      dockerfile: ops/docker/nextjs/Dockerfile
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      - APP_ENV=${APP_ENV}
